fnr=input("Give me the first number: ")
snr=input("Give me the second number: ")
print("Thank you!")
fn=int(fnr)
sn=int(snr)
print(f"{fn} + {sn} = {fn+sn}")
print(f"{fn} - {sn} = {fn-sn}")
print(f"{fn} / {sn} = {fn/sn}")
print(f"{fn} * {sn} = {fn*sn}")
